#!/bin/bash
# vi: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :

function help(){
    echo "Type $0 num ( 0 <= num <= 4294967295 )" >&2
    exit 1
}

arg="$1"

if [[ ! ( "${arg:-x}" =~ ^[0-9]{1,10}$ ) ]]; then
    echo "Invalid argument." >&2
    help
fi

if [ "$arg" -lt 0 ] || [ "$arg" -gt 4294967295 ]; then
    echo "Invalid number." >&2
    help
fi

printf "%d.%d.%d.%d\n" \
    $(( arg >> 24 )) \
    $(( ( arg >> 16 ) & 0xFF )) \
    $(( ( arg >>  8 ) & 0xFF )) \
    $(( arg & 0xFF ))
