#!/bin/bash
# vi: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :

pdir="$( dirname "$0" )"
DEC2IP="${pdir}/dec2ip"
IP2DEC="${pdir}/ip2dec"
CIDR2NET="${pdir}/cidr2netmask"
for c in "$DEC2IP" "$IP2DEC" "$CIDR2NET"
do
    if [ ! -x "$c" ]; then
        echo "Not found $c" >&2
        exit 1
    fi
done

function help(){
    cat <<_HELP >&2
Usage:
    $0 ipv4addr_range

 Examples:
    $0 192.168.54.0/20

    $0 192.168.54.54/255.255.255.248

_HELP
    exit 1
}

range="$1"

network="$( echo "$range" | awk -F'/' '{print $1}' )"
mask="$( echo "$range" | awk -F'/' '{print $2}' )"

if [ -z "${mask:=255.255.255.255}" ]; then
    mask_dec="$( "$IP2DEC" "$mask" )"
elif [[ "$mask" =~ ^[0-9]{1,2}$ ]]; then
    mask="$( "$CIDR2NET" "$mask" 2> /dev/null )"
    mask_dec="$( "$IP2DEC" "$mask" 2> /dev/null )"
else
    mask_dec="$( "$IP2DEC" "$mask" 2> /dev/null )"
fi
network_dec="$( "$IP2DEC" "$network"  2> /dev/null)"

if [ -z "$network_dec" ] || [ -z "$mask_dec" ]; then
    help
fi

s_network="$( "$DEC2IP" "$(( network_dec & mask_dec ))" )"
e_network="$( "$DEC2IP" "$(( network_dec | (0xFFFFFFFF ^ mask_dec ) ))" )"

echo "$s_network $e_network $mask"
