#!/bin/bash
# vi: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :

function help(){
    echo "type like $0 192.168.1.3"
    exit 1
}

function ip2decimal(){
    local addr="$1"
    local n="$addr"
    local IFS=.

    printf "%s\n" $(( \
                      ( n[0] << 24 ) \
                    | ( n[1] << 16 ) \
                    | ( n[2] << 8 ) \
                    | ( n[3] ) \
                    ))
}

function chkarg(){
    local addr="$1"
    local n="$addr"
    local IFS=.

    if [ "${n[0]}" -lt 0 ] \
      || [ "${n[1]}" -lt 0 ] \
      || [ "${n[2]}" -lt 0 ] \
      || [ "${n[3]}" -lt 0 ] \
      || [ "${n[0]}" -gt 255 ] \
      || [ "${n[1]}" -gt 255 ] \
      || [ "${n[2]}" -gt 255 ] \
      || [ "${n[3]}" -gt 255 ] ; then
        echo "Invalid argument."
        help
    fi
}

arg="$1"
if [ -z "$arg" ]; then
    help
fi

if [[ ! ("$arg" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$) ]]; then
    echo "Invalid argument."
    help
fi

chkarg "$arg"
ip2decimal "$arg"
