#!/bin/bash
# vi: set ts=4 sw=4 sts=0 et ft=sh fenc=utf-8 ff=unix :

function help() {
    echo "type like $0 192.168.1.3" >&2
    exit 1
}

function ip2decimal() {
    local addr="$1"
    local IFS=.
    # shellcheck disable=SC2206
    local n=($addr)

    if [ "${n[0]}" -lt 0 ] \
        || [ "${n[1]}" -lt 0 ] \
        || [ "${n[2]}" -lt 0 ] \
        || [ "${n[3]}" -lt 0 ] \
        || [ "${n[0]}" -gt 255 ] \
        || [ "${n[1]}" -gt 255 ] \
        || [ "${n[2]}" -gt 255 ] \
        || [ "${n[3]}" -gt 255 ]; then
        echo "Invalid argument." >&2
        help
    fi

    printf "%s\n" $(((\
    n[0] << 24) | (\
    n[1] << 16) | (\
    n[2] << 8) | (\
    n[3])))
}

arg="$1"
if [ -z "$arg" ]; then
    help
fi

if [[ ! ("$arg" =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$) ]]; then
    echo "Invalid argument." >&2
    help
fi

ip2decimal "$arg"
